version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - 'aws --version'
      - 'curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"'
      - 'unzip -q awscliv2.zip'
      - './aws/install'
      - 'aws --version'
  build:
    commands: |
       set -e
       while IFS=, read -r dockerImage ecrImage tag
       do
       echo "$dockerImage:$tag"
       docker pull $dockerImage:$tag
       docker tag $dockerImage:$tag $ecrImage:$tag
       aws ecr get-login-password | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
       docker push $ecrImage:$tag
       done < images.csv