version: 0.2
env: 
  ${secret_options}
phases:
  install:
    commands:
      - wget https://github.com/google/go-containerregistry/releases/download/${crane_version}/go-containerregistry_Linux_x86_64.tar.gz -nv -O ./crane.tar.gz
      - tar -xf crane.tar.gz
  build:
    commands: |
      set -e
      while IFS=, read -r dockerImage ecrImage tag
      do
      if [ ! -v $${DOCKER_HUB_PASSWORD} ]; then ./crane auth login docker.io -u $${DOCKER_HUB_USERNAME} -p $${DOCKER_HUB_PASSWORD}; fi
      if [ ! -v $${DOCKER_HUB_PASSWORD} ] && [ "$${LOGGING}" == "debug" ]; then TOKEN=$(curl --user $${DOCKER_HUB_USERNAME}:$${DOCKER_HUB_PASSWORD} "https://auth.docker.io/token?service=registry.docker.io&scope=repository:ratelimitpreview/test:pull" | jq -r .token);fi
      PWD=$(aws ecr get-login-password) 
      ./crane auth login -u AWS -p $${PWD} $${AWS_ACCOUNT_ID}.dkr.ecr.$${AWS_REGION}.amazonaws.com
      echo "$dockerImage:$tag"
      ./crane copy $dockerImage:$tag $ecrImage:$tag --platform linux/amd64
      if [ ! -v $TOKEN ] && [ "$${LOGGING}" == "debug" ] ;then curl --head -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest 2>&1 | grep RateLimit; fi
      done < images.csv
