# This is a basic workflow to help you get started with Actions

name: Terraform

# Controls when the action will run. 
on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
      - name: Terraform security scan
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          tfsec_args: --concise-output
          soft_fail: false

      - name: Terraform pr commenter
        uses: aquasecurity/tfsec-pr-commenter-action@v1.0.2
        with:
          tfsec_args: --concise-output
          github_token: ${{ github.token }}